(()=>{
  if(document.getElementById('fdcc-panel')) return;
  const players=globalThis.FDCC_PLAYERS||[]; const E=globalThis.FDCC;
  const state={slot:1,autosync:'on',status:{},history:[],pick:1,seen:new Set(),seenLines:new Set()};
  const panel=document.createElement('aside');panel.id='fdcc-panel';panel.innerHTML=`<div class="toprow"><div><h2>Draft Command Center</h2><div class="muted" id="fdcc-sub">Loading settings…</div></div><button class="close" id="fdcc-close" title="Hide">×</button></div><section><div class="toprow"><strong id="fdcc-clock">Pick 1.01</strong><span id="fdcc-next" class="muted"></span></div><div id="fdcc-sync" class="mini">Auto-sync checking ESPN…</div></section><section><strong>Best available</strong><div id="fdcc-recs"></div></section><section><strong>Rapid mode</strong><div class="mini">Type a player. Enter = Other. Click Mine for your selection.</div><div class="actions"><input id="fdcc-search" placeholder="e.g. Bijan"><button class="mine" id="fdcc-mine">Mine</button></div><div id="fdcc-match" class="mini"></div></section><section><strong>Bulk catch-up</strong><textarea id="fdcc-bulk" placeholder="Paste one drafted player per line"></textarea><button id="fdcc-process">Process picks</button></section><section><div class="toprow"><strong>My roster</strong><button id="fdcc-undo">Undo</button></div><div class="roster" id="fdcc-roster"></div></section><div class="status" id="fdcc-status" aria-live="polite"></div>`;document.documentElement.appendChild(panel);
  const $=s=>panel.querySelector(s);
  chrome.storage.local.get({fdccSlot:1,fdccAutosync:'on',fdccDraftState:null},v=>{state.slot=v.fdccSlot;state.autosync=v.fdccAutosync;if(v.fdccDraftState){Object.assign(state,v.fdccDraftState);state.seen=new Set(v.fdccDraftState.seen||[]);state.seenLines=new Set(v.fdccDraftState.seenLines||[])}render();startObserver();});
  function save(){chrome.storage.local.set({fdccDraftState:{slot:state.slot,autosync:state.autosync,status:state.status,history:state.history,pick:state.pick,seen:[...state.seen],seenLines:[...state.seenLines]}})}
  function labelPick(n){const r=Math.floor((n-1)/12)+1,p=(n-1)%12+1;return `${r}.${String(p).padStart(2,'0')}`}
  function setStatus(t,warn=false){const el=$('#fdcc-status');el.textContent=t;el.className='status'+(warn?' warning':'')}
  function mark(p,owner='other',source='manual'){
    if(!p||state.status[p.id])return false;state.status[p.id]=owner;state.history.push({id:p.id,owner,pick:state.pick,source});state.pick++;state.seen.add(E.normalize(p.name));save();render();return true;
  }
  function undo(){const h=state.history.pop();if(!h)return setStatus('Nothing to undo.');delete state.status[h.id];state.pick=Math.max(1,h.pick);const p=players.find(x=>x.id===h.id);if(p)state.seen.delete(E.normalize(p.name));save();render();setStatus(`Undid ${p?p.name:'last pick'}.`)}
  function currentMatch(){return E.matchPlayer($('#fdcc-search').value,players.filter(p=>!state.status[p.id]))}
  function rapid(owner){const p=currentMatch();if(!p)return setStatus('No available player match.',true);mark(p,owner,'rapid');$('#fdcc-search').value='';$('#fdcc-match').textContent='';$('#fdcc-search').focus();setStatus(`${p.name} → ${owner==='mine'?'MY TEAM':'other team'}`)}
  function processBulk(){const lines=$('#fdcc-bulk').value.split(/\n|,/).map(x=>x.trim()).filter(Boolean);let done=0,miss=[];for(const line of lines){const p=E.matchPlayer(line,players.filter(x=>!state.status[x.id]));if(p){const owner=E.teamAtPick(state.pick)===state.slot?'mine':'other';if(mark(p,owner,'bulk'))done++;else miss.push(line)}else miss.push(line)}$('#fdcc-bulk').value='';setStatus(`${done} picks processed${miss.length?`; not matched: ${miss.join(', ')}`:''}`,!!miss.length)}
  function render(){
    $('#fdcc-sub').textContent=`12-team PPR • slot ${state.slot} • auto-sync ${state.autosync}`;$('#fdcc-clock').textContent=`Current ${labelPick(state.pick)}`;const np=E.nextPickForSlot(state.pick,state.slot);$('#fdcc-next').textContent=np?`You: ${np===state.pick?'ON CLOCK':`in ${np-state.pick} picks`}`:'Draft complete';
    const recs=E.recommend(players,state.status,state.pick,state.slot).slice(0,5);const box=$('#fdcc-recs');box.innerHTML='';recs.forEach((p,i)=>{const d=document.createElement('div');d.className='rec'+(i===0?' best':'');d.innerHTML=`<span class="score">${p.score}</span><strong>${i+1}. ${p.name}</strong><div class="mini">${p.pos} • ${p.team} • rank ${p.rank}</div><div class="mini">Make-it-back estimate: ${p.returnChance}%</div><div class="bar"><span style="width:${p.returnChance}%"></span></div>`;box.appendChild(d)});
    const mine=players.filter(p=>state.status[p.id]==='mine');const c=E.counts(mine);const flexPool=mine.filter(p=>['RB','WR','TE'].includes(p.pos)).length;const slots=[['QB',c.QB],['RB',c.RB],['WR',c.WR],['TE',c.TE],['FLEX',Math.max(0,flexPool-5)],['DST',c.DST],['K',c.K],['BENCH',Math.max(0,mine.length-9)],['IR',0]];$('#fdcc-roster').innerHTML=slots.map(([k,v])=>`<div class="pill"><strong>${k}</strong> ${v}</div>`).join('');
  }
  function candidateSelectionLines(){
    const selectors=['[class*="activity" i]','[class*="draft-log" i]','[class*="draftLog" i]','[aria-label*="draft" i] [role="listitem"]','[data-testid*="pick" i]'];
    const nodes=[...new Set(selectors.flatMap(s=>{try{return [...document.querySelectorAll(s)]}catch{return []}}))].slice(-300);
    const lines=[];
    for(const node of nodes){const text=(node.innerText||'').trim();if(!text||text.length>320)continue;const lower=text.toLowerCase();if(!/(selected|drafted|chose|chooses|selection|picked\s)/i.test(lower))continue;for(const line of text.split('\n').map(x=>x.trim()).filter(Boolean)){if(line.length<=180&&/(selected|drafted|chose|chooses|selection|picked\s)/i.test(line))lines.push(line)}}
    return [...new Set(lines)];
  }
  function scanESPN(){
    if(state.autosync!=='on')return;let caught=0;const lines=candidateSelectionLines();for(const line of lines){const key=E.normalize(line);if(!key||state.seenLines.has(key))continue;const p=E.matchPlayer(line,players.filter(x=>!state.status[x.id]));if(!p)continue;state.seenLines.add(key);const owner=E.teamAtPick(state.pick)===state.slot?'mine':'other';if(mark(p,owner,'espn-auto'))caught++}
    if(caught){$('#fdcc-sync').textContent=`Auto-sync caught ${caught} new pick${caught===1?'':'s'}.`;setStatus(`ESPN auto-sync updated ${caught} selection${caught===1?'':'s'}.`)}else if(!state.history.length){$('#fdcc-sync').textContent='Watching ESPN selection log. Rapid mode is ready as backup.'}
  }
  function startObserver(){scanESPN();const obs=new MutationObserver(()=>{clearTimeout(startObserver.t);startObserver.t=setTimeout(scanESPN,220)});obs.observe(document.body,{subtree:true,childList:true,characterData:true});setInterval(scanESPN,2500)}
  $('#fdcc-search').addEventListener('input',()=>{const p=currentMatch();$('#fdcc-match').textContent=p?`Match: ${p.name} • ${p.pos} • ${p.team}`:''});$('#fdcc-search').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();rapid('other')}});$('#fdcc-mine').addEventListener('click',()=>rapid('mine'));$('#fdcc-process').addEventListener('click',processBulk);$('#fdcc-undo').addEventListener('click',undo);$('#fdcc-close').addEventListener('click',()=>panel.remove());
})();
